[package]
name = "megadocker"
version = "0.5.0"
description = "Microservices builder"
authors = ["George Georgulas IV"]
license = ""
repository = ""
default-run = "megadocker"
build = "src/build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
rustfmt = { version = "0.10.0" }
tauri-build = { version = "1.0.0-beta.4" }

[dependencies]
serde_json = "1.0.75"
serde = { version = "1.0.133", features = ["derive"] }
tauri = { version = "1.0.0-beta.8", features = ["fs-write-binary-file", "updater"] }

[features]
default = [ "custom-protocol" ]
custom-protocol = [ "tauri/custom-protocol" ]
