//  IMemoryMarker.rs
//  MEGADocker
//  a union type of string literals that represents the location of a memory value in the mites
//  Created by George Georgulas IV on 3/11/21.
//  Automatically ported to Rust by chatGPT on 1/8/23.
//  Copyright © 2019-2023 The MegaDocker Group. All rights reserved.

// TODO: this file must be verified vs it's original version's string literal values.  The original TypeScript version of the file is below in the last comment of the file

pub type memory_marker_union = &'static str;

pub const AUTHELIA_MARIA_DB_PASSWORD: IMemoryMarker = "[[AUTHELIAMARIADBPASSWORD]]";
pub const AUTHELIA_MARIA_DB_ROOT_PASSWORD: IMemoryMarker = "[[AUTHELIAMARIADBROOTPASSWORD]]";
pub const AUTHELIA_MARIA_DB_USER: IMemoryMarker = "[[AUTHELIAMARIADBUSER]]";
pub const AUTHELIA_REDIS_PASSWORD: IMemoryMarker = "[[AUTHELIAREDISPASSWORD]]";
pub const AUTHELIA_REDIS_USER: IMemoryMarker = "[[AUTHELIAREDISUSER]]";
pub const CLOUDFLARE_API_KEY: IMemoryMarker = "[[CLOUDFLAREAPIKEY]]";
pub const CLOUDFLARE_API_TOKEN: IMemoryMarker = "[[CLOUDFLAREAPITOKEN]]";
pub const CLOUDFLARE_EMAIL: IMemoryMarker = "[[CLOUDFLAREEMAIL]]";
pub const DRUPAL_POSTGRES_PASSWORD: IMemoryMarker = "[[DRUPALPOSTGRESPASSWORD]]";
pub const DRUPAL_POSTGRES_USER: IMemoryMarker = "[[DRUPALPOSTGRESUSER]]";
pub const GHOST_MARIA_DB_ROOT_PASSWORD: IMemoryMarker = "[[GHOSTMARIADBROOTPASSWORD]]";
pub const GITLAB_POSTGRES_PASSWORD: IMemoryMarker = "[[GITLABPOSTGRESPASSWORD]]";
pub const GITLAB_POSTGRES_USER: IMemoryMarker = "[[GITLABPOSTGRESUSER]]";
pub const GITLAB_ROOT_EMAIL: IMemoryMarker = "[[GITLABROOTEMAIL]]";
pub const GITLAB_ROOT_PASSWORD: IMemoryMarker = "[[GITLABROOTPASSWORD]]";
pub const KANBOARD_MARIA_DB_USER: IMemoryMarker = "[[KANBOARDMARIADBUSER]]";
pub const KANBOARD_MARIA_DB_PASSWORD: IMemoryMarker = "[[KANBOARDMARIADBPASSWORD]]";
pub const KANBOARD_MARIA_DB_ROOT_PASSWORD: IMemoryMarker = "[[KANBOARDMARIADBROOTPASSWORD]]";
pub const KIBANA_PASSWORD: IMemoryMarker = "[[KIBANAPASSWORD]]";
pub const KIBANA_USER: IMemoryMarker = "[[KIBANAUSER]]";
pub const LDAP_ADMIN_PASSWORD: IMemoryMarker = "[[LDAPADMINPASSWORD]]";
pub const LDAP_ADMIN_USERNAME: IMemoryMarker = "[[LDAPADMINUSERNAME]]";
pub const LDAP_DOMAIN_AS_DCS: IMemoryMarker = "[[LDAPDOMAINASDCS]]";
pub const LDAP_AUTH_ELIA_SESSION_SECRET: IMemoryMarker = "[[LDAPAUTHELIASESSIONSECRET]]";
pub const LDAP_CONFIGURATION_PASSWORD: IMemoryMarker = "[[LDAPCONFIGURATIONPASSWORD]]";
pub const LDAP_JWT_SECRET: IMemoryMarker = "[[LDAPJWTSECRET]]";
pub const LDAP_MAIL_USERNAME: IMemoryMarker = "[[LDAPMAILUSERNAME]]";
pub const LDAP_MAIL_DOMAIN: IMemoryMarker = "[[LDAPMAILDOMAIN]]";
pub const LDAP_ORGANISATION: IMemoryMarker = "[[LDAPORGANISATION]]";
pub const LDAP_SMTP_HOST: IMemoryMarker = "[[LDAPSMTPHOST]]";
pub const LDAP_SMTP_PASSWORD: IMemoryMarker = "[[LDAPSMTPASSWORD]]";
pub const LEDGER_POSTGRES_PASSWORD: IMemoryMarker = "[[LEDGERPOSTGRESPASSWORD]]";
pub const LEDGER_POSTGRES_USER: IMemoryMarker = "[[LEDGERPOSTGRESUSER]]";
pub const LETS_ENCRYPT_EMAIL: IMemoryMarker = "[[LETSENCRYPTEMAIL]]";
pub const LUA_DNS_API_TOKEN: IMemoryMarker = "[[LUADNSAPITOKEN]]";
pub const LUA_DNS_EMAIL_ADDRESS: IMemoryMarker = "[[LUADNSEMAILADDRESS]]";
pub const MEMORY_PLACEHOLDER: IMemoryMarker = "[[MEMORYPLACEHOLDER]]";
pub const MOB_FOLDER_PATH: IMemoryMarker = "[[MOBFOLDERPATH]]";
pub const MOB_NAME: IMemoryMarker = "[[MOBNAME]]";
pub const N8N_USERNAME: IMemoryMarker = "[[N8NUSERNAME]]";
pub const N8N_PASSWORD: IMemoryMarker = "[[N8NPASSWORD]]";
const NEXTCLOUD_MARIA_DB_PASSWORD: IMemoryMarker = "[[NEXTCLOUDMARIADBPASSWORD]]";
pub const NEXTCLOUD_MARIA_DB_ROOT_PASSWORD: IMemoryMarker = "[[NEXTCLOUDMARIADBROOTPASSWORD]]";
pub const NEXTCLOUD_MARIA_DB_USER: IMemoryMarker = "[[NEXTCLOUDMARIADBUSER]]";
pub const NEXTCLOUD_POSTGRES_PASSWORD: IMemoryMarker = "[[NEXTCLOUDPOSTGRESPASSWORD]]";
pub const NEXTCLOUD_POSTGRES_USER: IMemoryMarker = "[[NEXTCLOUDPOSTGRESUSER]]";
pub const OPEN_SOURCE_POS_MARIA_DB_PASSWORD: IMemoryMarker = "[[OPENSOURCEPOSMARIADBPASSWORD]]";
pub const OPEN_SOURCE_POS_MARIA_DB_USER: IMemoryMarker = "[[OPENSOURCEPOSMARIADBUSER]]";
pub const OPEN_SOURCE_POS_MARIA_DB_ROOT_PASSWORD: IMemoryMarker = "[[OPENSOURCEPOSMARIADBROOTPASSWORD]]";
pub const PI_HOLE_PASSWORD: IMemoryMarker = "[[PIHOLEPASSWORD]]";
pub const PRIMARY_DOMAIN: IMemoryMarker = "[[PRIMARYDOMAIN]]";
pub const ROCKET_CHAT_BOT_PASSWORD: IMemoryMarker = "[[ROCKETCHATBOTPASSWORD]]";
pub const ROCKET_CHAT_BOT_USERNAME: IMemoryMarker = "[[ROCKETCHATBOTUSERNAME]]";
pub const SWARM_PIT_COUCHBASE_PASSWORD: IMemoryMarker = "[[SWARMPITCOUCHBASEPASSWORD]]";
pub const VSCODE_PASSWORD: IMemoryMarker = "[[VSCODEPASSWORD]]";
pub const WEBDAV_USER: IMemoryMarker = "[[WEBDAVUSER]]";
pub const WEBDAV_PASSWORD: IMemoryMarker = "[[WEBDAVPASSWORD]]";
pub const WORDPRESS_MARIA_DB_PASSWORD: IMemoryMarker = "[[WORDPRESSMARIADBPASSWORD]]";
pub const WORDPRESS_MARIA_DB_ROOT_PASSWORD: IMemoryMarker = "[[WORDPRESSMARIADBROOTPASSWORD]]";
pub const WORDPRESS_MARIA_DB_USER: IMemoryMarker = "[[WORDPRESMARIADBUSER]]";

/*
export type IMemoryMarker =
  | `[[AUTHELIAMARIADBPASSWORD]]`
  | `[[AUTHELIAMARIADBROOTPASSWORD]]`
  | `[[AUTHELIAMARIADBUSER]]`
  | `[[AUTHELIAREDISPASSWORD]]`
  | `[[AUTHELIAREDISUSER]]`
  | `[[CLOUDFLAREAPIKEY]]`
  | `[[CLOUDFLAREAPITOKEN]]`
  | `[[CLOUDFLAREEMAIL]]`
  | `[[DRUPALPOSTGRESPASSWORD]]`
  | `[[DRUPALPOSTGRESUSER]]`
  | `[[GHOSTMARIADBROOTPASSWORD]]`
  | `[[GITLABPOSTGRESPASSWORD]]`
  | `[[GITLABPOSTGRESUSER]]`
  | `[[GITLABROOTEMAIL]]`
  | `[[GITLABROOTPASSWORD]]`
  | `[[KANBOARDMARIADBUSER]]`
  | `[[KANBOARDMARIADBPASSWORD]]`
  | `[[KANBOARDMARIADBROOTPASSWORD]]`
  | `[[KIBANAPASSWORD]]`
  | `[[KIBANAUSER]]`
  | `[[LDAPADMINPASSWORD]]`
  | `[[LDAPADMINUSERNAME]]`
  | `[[LDAPDOMAINASDCS]]` // NOTE only used in ldif and conf files
  | `[[LDAPAUTHELIASESSIONSECRET]]`
  | `[[LDAPCONFIGURATIONPASSWORD]]`
  | `[[LDAPJWTSECRET]]`
  | `[[LDAPMAILUSERNAME]]`
  | `[[LDAPMAILDOMAIN]]`
  | `[[LDAPORGANISATION]]`
  | `[[LDAPSMTPHOST]]`
  | `[[LDAPSMTPASSWORD]]`
  | `[[LEDGERPOSTGRESPASSWORD]]`
  | `[[LEDGERPOSTGRESUSER]]`
  | `[[LETSENCRYPTEMAIL]]`
  | `[[LUADNSAPITOKEN]]`
  | `[[LUADNSEMAILADDRESS]]`
  | `[[MEMORYPLACEHOLDER]]`
  | `[[MOBFOLDERPATH]]`
  | `[[MOBNAME]]`
  | `[[N8NUSERNAME]]`
  | `[[N8NPASSWORD]]`
  | `[[NEXTCLOUDMARIADBPASSWORD]]`
  | `[[NEXTCLOUDMARIADBROOTPASSWORD]]`
  | `[[NEXTCLOUDMARIADBUSER]]`
  | `[[NEXTCLOUDPOSTGRESPASSWORD]]`
  | `[[NEXTCLOUDPOSTGRESUSER]]`
  | `[[OPENSOURCEPOSMARIADBPASSWORD]]`
  | `[[OPENSOURCEPOSMARIADBUSER]]`
  | `[[OPENSOURCEPOSMARIADBROOTPASSWORD]]`
  | `[[PIHOLEPASSWORD]]`
  | `[[PRIMARYDOMAIN]]`
  | `[[ROCKETCHATBOTPASSWORD]]`
  | `[[ROCKETCHATBOTUSERNAME]]`
  | `[[SWARMPITCOUCHBASEPASSWORD]]`
  | `[[VSCODEPASSWORD]]`
  | `[[WEBDAVUSER]]`
  | `[[WEBDAVPASSWORD]]`
  | `[[WORDPRESSMARIADBPASSWORD]]`
  | `[[WORDPRESSMARIADBROOTPASSWORD]]`
  | `[[WORDPRESSMARIADBUSER]]` */