/** @format */

//  IMemoryMarker.ts
//  MegaDocker
//  a union type of strings that represent a memory value in the mites
//  Created by George Georgulas IV on 3/11/21.
//  Copyright © 2021 The MegaDocker Group. All rights reserved.

export type IMemoryMarker =
  | `[[AUTHELIAMARIADBPASSWORD]]`
  | `[[AUTHELIAMARIADBROOTPASSWORD]]`
  | `[[AUTHELIAMARIADBUSER]]`
  | `[[CLOUDFLAREAPIKEY]]`
  | `[[CLOUDFLAREAPITOKEN]]`
  | `[[CLOUDFLAREEMAIL]]`
  | `[[DRUPALPOSTGRESPASSWORD]]`
  | `[[DRUPALPOSTGRESUSER]]`
  | `[[GHOSTMARIADBROOTPASSWORD]]`
  | `[[GITLABPOSTGRESPASSWORD]]`
  | `[[GITLABPOSTGRESUSER]]`
  | `[[GITLABROOTEMAIL]]`
  | `[[GITLABROOTPASSWORD]]`
  | `[[KANBOARDMARIADBUSER]]`
  | `[[KANBOARDMARIADBPASSWORD]]`
  | `[[KANBOARDMARIADBROOTPASSWORD]]`
  | `[[KIBANAPASSWORD]]`
  | `[[KIBANAUSER]]`
  | `[[LDAPADMINPASSWORD]]`
  | `[[LDAPADMINUSERNAME]]`
  | `[[LDAPAUTHELIASESSIONSECRET]]`
  | `[[LDAPCONFIGURATIONPASSWORD]]`
  | `[[LDAPJWTSECRET]]`
  | `[[LDAPMAILUSERNAME]]`
  | `[[LDAPMAILDOMAIN]]`
  | `[[LDAPORGANISATION]]`
  | `[[LDAPSMTPHOST]]`
  | `[[LDAPSMTPASSWORD]]`
  | `[[LEDGERPOSTGRESPASSWORD]]`
  | `[[LEDGERPOSTGRESUSER]]`
  | `[[LETSENCRYPTEMAIL]]`
  | `[[MOBFOLDERPATH]]`
  | `[[MOBNAME]]`
  | `[[N8NUSERNAME]]`
  | `[[N8NPASSWORD]]`
  | `[[NEXTCLOUDMARIADBPASSWORD]]`
  | `[[NEXTCLOUDMARIADBROOTPASSWORD]]`
  | `[[NEXTCLOUDMARIADBUSER]]`
  | `[[NEXTCLOUDPOSTGRESPASSWORD]]`
  | `[[NEXTCLOUDPOSTGRESUSER]]`
  | `[[OPENSOURCEPOSMARIADBPASSWORD]]`
  | `[[OPENSOURCEPOSMARIADBUSER]]`
  | `[[OPENSOURCEPOSMARIADBROOTPASSWORD]]`
  | `[[PIHOLEPASSWORD]]`
  | `[[PRIMARYDOMAIN]]`
  | `[[ROCKETCHATBOTPASSWORD]]`
  | `[[ROCKETCHATBOTUSERNAME]]`
  | `[[SWARMPITCOUCHBASEPASSWORD]]`
  | `[[VSCODEPASSWORD]]`
  | `[[WEBDAVUSER]]`
  | `[[WEBDAVPASSWORD]]`
  | `[[WORDPRESSMARIADBPASSWORD]]`
  | `[[WORDPRESSMARIADBROOTPASSWORD]]`
  | `[[WORDPRESSMARIADBUSER]]`
